export default {
  CREATE_COURSE: "CREATE_COURSE",
  LOAD_COURSES: "LOAD_COURSES",
  UPDATE_COURSE: "UPDATE_COURSE",
  DELETE_COURSE: "DELETE_COURSE",
  LOAD_AUTHORS: "LOAD_AUTHORS",
  DELETE_AUTHORS: "DELETE_AUTHORS",
  UPDATE_AUTHOR: "UPDATE_AUTHOR",
  CREATE_AUTHOR: "CREATE_AUTHOR"
};